image:
  file: .docker/Dockerfile

ports:
  - port: 8080

tasks:
  - init: npm install

vscode:
  extensions:
    - christian-kohler.path-intellisense@1.4.2:QnOrf5fk6KiVaQs4cNEP+w==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
    - mrmlnc.vscode-scss@0.9.0:/wXbNRm+2kunH5HbQqfnXA==
    - PKief.material-icon-theme@3.9.2:xeHlNzPEF04yFqz/xKCD5w==
    - Ionide.Ionide-fsharp@4.5.0:0qxXuhq6eO066etkNQrKCQ==
    - zhuangtongfa.material-theme@3.2.2:jGTZwg0ChZg3eEKHC+UO+w==
    - mhutchie.git-graph@1.21.0:zoSeoEOMfrwN0BMBC8VvqQ==
    - eamodio.gitlens@10.2.0:GNDO73Cmp0fYDiLNxVkbsQ==
